site_name: Basic Unix for CS2030/S
site_url: https://ong6.github.io/Unix-Guide/
site_author: Ooi Wei Tsang
site_description: "All basic Unix commands"
repo_url: "https://github.com/ong6/Unix-Guide"
copyright:
  "This content is licensed under <a
  href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons
  Attribution-NonCommercial-ShareAlike 4.0 International</a> license."

theme:
  name: cinder
  colorscheme: github
  highlightjs: false
  hljs_languages:
    - PowerShell
    - Bash

shortcuts:
  previous: 72 # h
  next: 76 # l
  search: 191 # /

nav:
  - Home: index.md
  - Setup:
      - Setup for Windows 10: wsl.md
      - Setup for macOS: mac.md
  - Notes:
      - 1. Terminal and Shell: basic-shell.md
      - 2. Path and Navigation: basic-path-nav.md
      - 3. File Management: basic-file-management.md
      - 4. Intro to Vim: basic-vim-intro.md
      - 5. Hands on with Vim: basic-vim-practice.md
  - Extra: extra.md

extra_css:
  - "css/ooiwt.css"

markdown_extensions:
  - admonition
  - fontawesome_markdown
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.highlight:
      linenums: false
  - pymdownx.inlinehilite
  - pymdownx.keys:
      key_map:
        {
          bang: "!",
          dollar: "$",
          parenthesis-left: "(",
          parenthesis-right: ")",
        }
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
